# Generated by Django 5.1.6 on 2025-08-21 18:15

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neurodivergentes', '0020_alter_monitoramento_mes_alter_pdi_status'),
        ('profissionais_app', '0004_alter_profissional_profissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora')),
                ('duracao_minutos', models.IntegerField(blank=True, choices=[(15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (480, 'Dia inteiro'), (0, 'Personalizado')], default=45, null=True, verbose_name='Duração')),
                ('duracao_personalizada', models.IntegerField(blank=True, help_text="Usado quando duração = 'Personalizado'", null=True, verbose_name='Duração personalizada (minutos)')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição curta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(blank=True, choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('faltou', 'Faltou')], default='agendado', max_length=20, verbose_name='Status')),
                ('recorrencia', models.CharField(blank=True, choices=[('', 'Sem recorrência'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=20, verbose_name='Recorrência')),
                ('enviar_copia_gestor', models.BooleanField(default=False, verbose_name='Enviar cópia ao gestor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('neurodivergente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neurodivergentes.neurodivergente', verbose_name='Paciente/Aluno')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais_app.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_hora_inicio', '-criado_em'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
