# Generated by Django 5.1.6 on 2025-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tenant_id',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
