# Generated by Django 5.1.6 on 2025-08-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_tenant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_hora_inicio', '-criado_em'], 'permissions': [('can_manage_all_schedules', 'Pode gerenciar agendas de todos os profissionais')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelManagers(
            name='agendamento',
            managers=[
            ],
        ),
    ]
