# Generated by Django 5.1.6 on 2025-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0019_neurodivergente_tipo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=8, help_text='Selecione o mês do PEI', verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='status',
            field=models.CharField(choices=[('ausente', 'Ausente'), ('iniciado', 'Iniciado'), ('em_andamento', 'Em Planejamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20, verbose_name='Status'),
        ),
    ]
