# Generated by Django 5.1.6 on 2025-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0021_alter_neurodivergente_ano_escolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurodivergente',
            name='motivo_inatividade',
            field=models.TextField(blank=True, help_text='Descreva o motivo da inatividade (ex: transferência de cidade, mudança de escola, etc.)', null=True, verbose_name='Motivo da Inatividade'),
        ),
        migrations.AlterField(
            model_name='neurodivergente',
            name='ano_escolar',
            field=models.CharField(blank=True, choices=[('bercario1', 'Berçário I'), ('bercario2', 'Berçário II'), ('maternal1', 'Maternal I'), ('maternal2', 'Maternal II'), ('jardim', 'Jardim'), ('pre1', 'Pré I'), ('pre2', 'Pré II'), ('1ano', '1º Ano'), ('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano'), ('6ano', '6º Ano'), ('7ano', '7º Ano'), ('8ano', '8º Ano'), ('9ano', '9º Ano')], max_length=50, null=True, verbose_name='Ano Escolar'),
        ),
    ]
