# Generated by Django 5.1.6 on 2025-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0022_neurodivergente_motivo_inatividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurodivergente',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Cidade e estado de nascimento (ex: São Paulo - SP)', max_length=100, null=True, verbose_name='Naturalidade'),
        ),
    ]
