# Generated by Django 5.1.6 on 2025-08-29 19:08

from django.db import migrations, models


def remove_unique_constraint(apps, schema_editor):
    """Remove the old unique constraint manually"""
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint exists and remove it
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM information_schema.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'neurodivergentes_monitoramento' 
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME LIKE '%neurodivergente%mes%ano%'
        """)
        constraints = cursor.fetchall()
        
        for constraint in constraints:
            cursor.execute(f"ALTER TABLE neurodivergentes_monitoramento DROP INDEX {constraint[0]}")


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0023_neurodivergente_naturalidade'),
    ]

    operations = [
        # Primeiro remove a constraint manualmente
        migrations.RunPython(remove_unique_constraint, migrations.RunPython.noop),
        
        # Remove o campo mes
        migrations.RemoveField(
            model_name='monitoramento',
            name='mes',
        ),
        
        # Altera as opções do modelo
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-ano'], 'verbose_name': 'PAEE', 'verbose_name_plural': 'PAEE'},
        ),
        
        # Cria a nova constraint
        migrations.AlterUniqueTogether(
            name='monitoramento',
            unique_together={('neurodivergente', 'ano')},
        ),
        
        migrations.AlterField(
            model_name='monitoramento',
            name='ano',
            field=models.IntegerField(default=2025, help_text='Selecione o ano do PAEE', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='neurodivergente',
            name='cor_pele',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], help_text='Selecione a cor da pele conforme autodeclaração', max_length=10, verbose_name='Cor da Pele'),
        ),
        migrations.AlterField(
            model_name='neurodivergente',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('brasileira', 'Brasileira'), ('estrangeira', 'Estrangeira')], help_text='Selecione se é brasileira ou estrangeira', max_length=20, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='neurodivergente',
            name='pais_origem',
            field=models.CharField(blank=True, help_text='Informe o país de origem caso seja estrangeiro', max_length=50, verbose_name='País de Origem'),
        ),
        migrations.AlterField(
            model_name='neurodivergente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Selecione o tipo sanguíneo se conhecido', max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
    ]
