# Generated by Django 5.1.6 on 2025-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0024_alter_monitoramento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Descreva o planejamento para esta meta/habilidade', null=True, verbose_name='Planejamento'),
        ),
    ]
